sudo: required
dist: trusty
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
before_install:
  - npm install -g semantic-release
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
after_script: 
  - npm run semantic-release 