sudo: required
dist: trusty
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: Testing
      script: npm run lint
    - stage: Testing
      script: npm run test-coverage
    - stage: Testing  
      script: npm run e2e 
    - stage: Deploy
      script: chmod ugo+x scripts/run-ionic-cloud-builds-on-pr-or-master.sh
      script: ./scripts/run-ionic-cloud-builds-on-pr-or-master.sh
after_script: 
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls   
 